version: "3.7"
services:
  gulp:
    image: node
    user: node
    working_dir: /home/node/app
    command: bash -c "npm install && node ./node_modules/gulp/bin/gulp.js watch"
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    
